CREATE DATABASE IF NOT EXISTS todo_db;
use todo_db;

CREATE TABLE IF NOT EXISTS tasks (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
task VARCHAR (50) NOT NULL,
task_date VARCHAR (30) NOT NULL,
completed boolean NOT NULL,
email VARCHAR(50) NOT NULL
);